name       : ilmbase
version    : 2.2.1
release    : 5
source     :
    - https://download.savannah.nongnu.org/releases/openexr/ilmbase-2.2.1.tar.gz : cac206e63be68136ef556c2b555df659f45098c159ce24804e9d5e9e0286609e
license    : BSD-3-Clause
component  : multimedia.library
summary    : Base libraries from ILM for OpenEXR
description: |
    Base libraries from ILM for OpenEXR
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
