name       : ilmbase
version    : 2.5.4
release    : 7
source     :
    - https://github.com/AcademySoftwareFoundation/openexr/archive/v2.5.4.tar.gz : dba19e9c6720c6f64fbc8b9d1867eaa75da6438109b941eefdc75ed141b6576d
license    : BSD-3-Clause
component  : multimedia.library
summary    : Base libraries from ILM for OpenEXR
description: |
    Base libraries from ILM (Industrial Light & Magic) software for OpenEXR.
setup      : |
    cd IlmBase
    %cmake_ninja
build      : |
    cd IlmBase
    %ninja_build
install    : |
    cd IlmBase
    %ninja_install
check      : |
    cd IlmBase
    %ninja_check
