name       : ilmbase
version    : 2.3.0
release    : 6
source     :
    - https://github.com/openexr/openexr/releases/download/v2.3.0/ilmbase-2.3.0.tar.gz : 456978d1a978a5f823c7c675f3f36b0ae14dba36638aeaa3c4b0e784f12a3862
license    : BSD-3-Clause
component  : multimedia.library
summary    : Base libraries from ILM for OpenEXR
description: |
    Base libraries from ILM for OpenEXR
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
